#ifndef TIPOERROR_H
#define TIPOERROR_H

enum tipoError {
    OK,
    ERROR_ENTRENADOR_YA_EXISTE,
    ERROR_SOCIO_YA_EXISTE,
    ERROR_ENTRENADOR_NO_EXISTE,
    ERROR_SOCIO_NO_EXISTE
};

#endif // TIPOERROR_H
